//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace MyProject.Ebaywebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EbayServiceSoap", Namespace="http://tempuri.org/")]
    public partial class EbayService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback methodEbayinfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EbayService() {
            this.Url = global::MyProject.Properties.Settings.Default.MyProject_Ebaywebservice_EbayService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event methodEbayinfoCompletedEventHandler methodEbayinfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/methodEbayinfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ebaydetails methodEbayinfo(string EbayId) {
            object[] results = this.Invoke("methodEbayinfo", new object[] {
                        EbayId});
            return ((Ebaydetails)(results[0]));
        }
        
        /// <remarks/>
        public void methodEbayinfoAsync(string EbayId) {
            this.methodEbayinfoAsync(EbayId, null);
        }
        
        /// <remarks/>
        public void methodEbayinfoAsync(string EbayId, object userState) {
            if ((this.methodEbayinfoOperationCompleted == null)) {
                this.methodEbayinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmethodEbayinfoOperationCompleted);
            }
            this.InvokeAsync("methodEbayinfo", new object[] {
                        EbayId}, this.methodEbayinfoOperationCompleted, userState);
        }
        
        private void OnmethodEbayinfoOperationCompleted(object arg) {
            if ((this.methodEbayinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.methodEbayinfoCompleted(this, new methodEbayinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ebaydetails {
        
        private string method_EbayProdIDField;
        
        private string method_EbayProdModelField;
        
        private string method_EbayProdTypeField;
        
        private string method_EbayProdNameField;
        
        private string method_EbayProdPriceField;
        
        private string method_EbayProdSpecField;
        
        /// <remarks/>
        public string method_EbayProdID {
            get {
                return this.method_EbayProdIDField;
            }
            set {
                this.method_EbayProdIDField = value;
            }
        }
        
        /// <remarks/>
        public string method_EbayProdModel {
            get {
                return this.method_EbayProdModelField;
            }
            set {
                this.method_EbayProdModelField = value;
            }
        }
        
        /// <remarks/>
        public string method_EbayProdType {
            get {
                return this.method_EbayProdTypeField;
            }
            set {
                this.method_EbayProdTypeField = value;
            }
        }
        
        /// <remarks/>
        public string method_EbayProdName {
            get {
                return this.method_EbayProdNameField;
            }
            set {
                this.method_EbayProdNameField = value;
            }
        }
        
        /// <remarks/>
        public string method_EbayProdPrice {
            get {
                return this.method_EbayProdPriceField;
            }
            set {
                this.method_EbayProdPriceField = value;
            }
        }
        
        /// <remarks/>
        public string method_EbayProdSpec {
            get {
                return this.method_EbayProdSpecField;
            }
            set {
                this.method_EbayProdSpecField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void methodEbayinfoCompletedEventHandler(object sender, methodEbayinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class methodEbayinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal methodEbayinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ebaydetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ebaydetails)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591