//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace MyProject.BBuyWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BestBuyServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BestBuyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback methodBBUYdetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BestBuyService() {
            this.Url = global::MyProject.Properties.Settings.Default.MyProject_BBuyWebservice_BestBuyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event methodBBUYdetailsCompletedEventHandler methodBBUYdetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/methodBBUYdetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BestBuydetails methodBBUYdetails(string BBUYid) {
            object[] results = this.Invoke("methodBBUYdetails", new object[] {
                        BBUYid});
            return ((BestBuydetails)(results[0]));
        }
        
        /// <remarks/>
        public void methodBBUYdetailsAsync(string BBUYid) {
            this.methodBBUYdetailsAsync(BBUYid, null);
        }
        
        /// <remarks/>
        public void methodBBUYdetailsAsync(string BBUYid, object userState) {
            if ((this.methodBBUYdetailsOperationCompleted == null)) {
                this.methodBBUYdetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmethodBBUYdetailsOperationCompleted);
            }
            this.InvokeAsync("methodBBUYdetails", new object[] {
                        BBUYid}, this.methodBBUYdetailsOperationCompleted, userState);
        }
        
        private void OnmethodBBUYdetailsOperationCompleted(object arg) {
            if ((this.methodBBUYdetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.methodBBUYdetailsCompleted(this, new methodBBUYdetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BestBuydetails {
        
        private string method_BBUYProdIdField;
        
        private string method_BBUYProdmodelField;
        
        private string method_BBUYProdtypeField;
        
        private string method_BBUYProdnameField;
        
        private string method_BBUYProdpriceField;
        
        /// <remarks/>
        public string method_BBUYProdId {
            get {
                return this.method_BBUYProdIdField;
            }
            set {
                this.method_BBUYProdIdField = value;
            }
        }
        
        /// <remarks/>
        public string method_BBUYProdmodel {
            get {
                return this.method_BBUYProdmodelField;
            }
            set {
                this.method_BBUYProdmodelField = value;
            }
        }
        
        /// <remarks/>
        public string method_BBUYProdtype {
            get {
                return this.method_BBUYProdtypeField;
            }
            set {
                this.method_BBUYProdtypeField = value;
            }
        }
        
        /// <remarks/>
        public string method_BBUYProdname {
            get {
                return this.method_BBUYProdnameField;
            }
            set {
                this.method_BBUYProdnameField = value;
            }
        }
        
        /// <remarks/>
        public string method_BBUYProdprice {
            get {
                return this.method_BBUYProdpriceField;
            }
            set {
                this.method_BBUYProdpriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void methodBBUYdetailsCompletedEventHandler(object sender, methodBBUYdetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class methodBBUYdetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal methodBBUYdetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BestBuydetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BestBuydetails)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591