//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace MyProject.Amazonwebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AmazonserviceSoap", Namespace="http://tempuri.org/")]
    public partial class Amazonservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback methodAMAZdetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Amazonservice() {
            this.Url = global::MyProject.Properties.Settings.Default.MyProject_Amazonwebservice_Amazonservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event methodAMAZdetailsCompletedEventHandler methodAMAZdetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/methodAMAZdetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Amazondetails methodAMAZdetails(string prod_id) {
            object[] results = this.Invoke("methodAMAZdetails", new object[] {
                        prod_id});
            return ((Amazondetails)(results[0]));
        }
        
        /// <remarks/>
        public void methodAMAZdetailsAsync(string prod_id) {
            this.methodAMAZdetailsAsync(prod_id, null);
        }
        
        /// <remarks/>
        public void methodAMAZdetailsAsync(string prod_id, object userState) {
            if ((this.methodAMAZdetailsOperationCompleted == null)) {
                this.methodAMAZdetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmethodAMAZdetailsOperationCompleted);
            }
            this.InvokeAsync("methodAMAZdetails", new object[] {
                        prod_id}, this.methodAMAZdetailsOperationCompleted, userState);
        }
        
        private void OnmethodAMAZdetailsOperationCompleted(object arg) {
            if ((this.methodAMAZdetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.methodAMAZdetailsCompleted(this, new methodAMAZdetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Amazondetails {
        
        private string method_AMAZProdidField;
        
        private string method_AMAZProdmodelField;
        
        private string method_AMAZProdtypeField;
        
        private string method_AMAZProdnameField;
        
        private string method_AMAZProdpriceField;
        
        /// <remarks/>
        public string method_AMAZProdid {
            get {
                return this.method_AMAZProdidField;
            }
            set {
                this.method_AMAZProdidField = value;
            }
        }
        
        /// <remarks/>
        public string method_AMAZProdmodel {
            get {
                return this.method_AMAZProdmodelField;
            }
            set {
                this.method_AMAZProdmodelField = value;
            }
        }
        
        /// <remarks/>
        public string method_AMAZProdtype {
            get {
                return this.method_AMAZProdtypeField;
            }
            set {
                this.method_AMAZProdtypeField = value;
            }
        }
        
        /// <remarks/>
        public string method_AMAZProdname {
            get {
                return this.method_AMAZProdnameField;
            }
            set {
                this.method_AMAZProdnameField = value;
            }
        }
        
        /// <remarks/>
        public string method_AMAZProdprice {
            get {
                return this.method_AMAZProdpriceField;
            }
            set {
                this.method_AMAZProdpriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void methodAMAZdetailsCompletedEventHandler(object sender, methodAMAZdetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class methodAMAZdetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal methodAMAZdetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Amazondetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Amazondetails)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591