//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace MyProject.Storewebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StoredetailsServiceSoap", Namespace="http://tempuri.org/")]
    public partial class StoredetailsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getstoredetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StoredetailsService() {
            this.Url = global::MyProject.Properties.Settings.Default.MyProject_Storewebservice_StoredetailsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getstoredetailsCompletedEventHandler getstoredetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getstoredetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Storedetails getstoredetails(string stid) {
            object[] results = this.Invoke("getstoredetails", new object[] {
                        stid});
            return ((Storedetails)(results[0]));
        }
        
        /// <remarks/>
        public void getstoredetailsAsync(string stid) {
            this.getstoredetailsAsync(stid, null);
        }
        
        /// <remarks/>
        public void getstoredetailsAsync(string stid, object userState) {
            if ((this.getstoredetailsOperationCompleted == null)) {
                this.getstoredetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetstoredetailsOperationCompleted);
            }
            this.InvokeAsync("getstoredetails", new object[] {
                        stid}, this.getstoredetailsOperationCompleted, userState);
        }
        
        private void OngetstoredetailsOperationCompleted(object arg) {
            if ((this.getstoredetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getstoredetailsCompleted(this, new getstoredetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Storedetails {
        
        private string method_storenameField;
        
        private string method_storestreetField;
        
        private string method_storecityField;
        
        private string method_storezipField;
        
        private string method_storephoneField;
        
        /// <remarks/>
        public string method_storename {
            get {
                return this.method_storenameField;
            }
            set {
                this.method_storenameField = value;
            }
        }
        
        /// <remarks/>
        public string method_storestreet {
            get {
                return this.method_storestreetField;
            }
            set {
                this.method_storestreetField = value;
            }
        }
        
        /// <remarks/>
        public string method_storecity {
            get {
                return this.method_storecityField;
            }
            set {
                this.method_storecityField = value;
            }
        }
        
        /// <remarks/>
        public string method_storezip {
            get {
                return this.method_storezipField;
            }
            set {
                this.method_storezipField = value;
            }
        }
        
        /// <remarks/>
        public string method_storephone {
            get {
                return this.method_storephoneField;
            }
            set {
                this.method_storephoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getstoredetailsCompletedEventHandler(object sender, getstoredetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getstoredetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getstoredetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Storedetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Storedetails)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591